/** Administrative districts of Madhya Pradesh (55 as of 2025–26). */
export const MADHYA_PRADESH_DISTRICTS = [
  'Agar Malwa',
  'Alirajpur',
  'Anuppur',
  'Ashoknagar',
  'Balaghat',
  'Barwani',
  'Betul',
  'Bhind',
  'Bhopal',
  'Burhanpur',
  'Chhatarpur',
  'Chhindwara',
  'Damoh',
  'Datia',
  'Dewas',
  'Dhar',
  'Dindori',
  'Guna',
  'Gwalior',
  'Harda',
  'Indore',
  'Jabalpur',
  'Jhabua',
  'Katni',
  'Khandwa',
  'Khargone',
  'Mandla',
  'Mandsaur',
  'Maihar',
  'Mauganj',
  'Morena',
  'Narmadapuram',
  'Narsinghpur',
  'Neemuch',
  'Niwari',
  'Panna',
  'Pandhurna',
  'Raisen',
  'Rajgarh',
  'Ratlam',
  'Rewa',
  'Sagar',
  'Satna',
  'Sehore',
  'Seoni',
  'Shahdol',
  'Shajapur',
  'Sheopur',
  'Shivpuri',
  'Sidhi',
  'Singrauli',
  'Tikamgarh',
  'Ujjain',
  'Umaria',
  'Vidisha',
] as const;

export type MadhyaPradeshDistrict = (typeof MADHYA_PRADESH_DISTRICTS)[number];

export const MADHYA_PRADESH_STATE = 'Madhya Pradesh';
